name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop 
jobs:
  check-application:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     go: ['1.14', '1.15']
    steps:
      - uses: actions/checkout@v2
        with:
          repository: rafael1mc/fc2.0-ci-go
          ref: main
          path: .github/workflows
      - uses: actions/setup-go@v2
        with:
          # go-version: ${{ matrix.go }}
          go-version: 1.15
      - run: go test
      - run: go run math.go