name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop 
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: My step to checkout
        uses: actions/checkout@v2
      - name: ${{ secrets.FOO_BAR }}
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: echo TRYING TO READ secret
      - run: echo you know $YO this
        env:
          YO: ${{ secrets.FOO_BAR }}
      - run: go test
      - run: go run math.go